[package]
name = "snapshot-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.51", features = ["derive"] }
crossbeam-channel = "0.5.15"
ignore = "0.4.25"

[dev-dependencies]
tempfile = "3.23.0"
